// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: characterRankings.proto

package warcraftlogs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CharacterRankingPage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page         uint32     `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	HasMorePages bool       `protobuf:"varint,2,opt,name=hasMorePages,proto3" json:"hasMorePages,omitempty"`
	Count        uint32     `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Rankings     []*Ranking `protobuf:"bytes,4,rep,name=rankings,proto3" json:"rankings,omitempty"`
}

func (x *CharacterRankingPage) Reset() {
	*x = CharacterRankingPage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_characterRankings_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterRankingPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterRankingPage) ProtoMessage() {}

func (x *CharacterRankingPage) ProtoReflect() protoreflect.Message {
	mi := &file_characterRankings_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterRankingPage.ProtoReflect.Descriptor instead.
func (*CharacterRankingPage) Descriptor() ([]byte, []int) {
	return file_characterRankings_proto_rawDescGZIP(), []int{0}
}

func (x *CharacterRankingPage) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CharacterRankingPage) GetHasMorePages() bool {
	if x != nil {
		return x.HasMorePages
	}
	return false
}

func (x *CharacterRankingPage) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CharacterRankingPage) GetRankings() []*Ranking {
	if x != nil {
		return x.Rankings
	}
	return nil
}

type Ranking struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Class         string             `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"`
	Spec          string             `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	Amount        float64            `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	HardModeLevel uint32             `protobuf:"varint,5,opt,name=hardModeLevel,proto3" json:"hardModeLevel,omitempty"`
	Duration      uint32             `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`
	StartTime     uint64             `protobuf:"varint,7,opt,name=startTime,proto3" json:"startTime,omitempty"`
	Report        *Ranking_Report    `protobuf:"bytes,8,opt,name=report,proto3" json:"report,omitempty"`
	Guild         *Ranking_Guild     `protobuf:"bytes,9,opt,name=guild,proto3" json:"guild,omitempty"`
	Server        *Ranking_Server    `protobuf:"bytes,10,opt,name=server,proto3" json:"server,omitempty"`
	BracketData   uint32             `protobuf:"varint,11,opt,name=bracketData,proto3" json:"bracketData,omitempty"`
	Faction       int32              `protobuf:"varint,12,opt,name=faction,proto3" json:"faction,omitempty"`
	Affixes       []uint32           `protobuf:"varint,13,rep,packed,name=affixes,proto3" json:"affixes,omitempty"`
	Medal         string             `protobuf:"bytes,14,opt,name=medal,proto3" json:"medal,omitempty"`
	Score         float64            `protobuf:"fixed64,15,opt,name=score,proto3" json:"score,omitempty"`
	Leaderboard   uint32             `protobuf:"varint,16,opt,name=leaderboard,proto3" json:"leaderboard,omitempty"`
	Talents       []*Ranking_Talents `protobuf:"bytes,17,rep,name=talents,proto3" json:"talents,omitempty"`
	Gear          []*Ranking_Gear    `protobuf:"bytes,18,rep,name=gear,proto3" json:"gear,omitempty"`
}

func (x *Ranking) Reset() {
	*x = Ranking{}
	if protoimpl.UnsafeEnabled {
		mi := &file_characterRankings_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ranking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ranking) ProtoMessage() {}

func (x *Ranking) ProtoReflect() protoreflect.Message {
	mi := &file_characterRankings_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ranking.ProtoReflect.Descriptor instead.
func (*Ranking) Descriptor() ([]byte, []int) {
	return file_characterRankings_proto_rawDescGZIP(), []int{1}
}

func (x *Ranking) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ranking) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *Ranking) GetSpec() string {
	if x != nil {
		return x.Spec
	}
	return ""
}

func (x *Ranking) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Ranking) GetHardModeLevel() uint32 {
	if x != nil {
		return x.HardModeLevel
	}
	return 0
}

func (x *Ranking) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Ranking) GetStartTime() uint64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Ranking) GetReport() *Ranking_Report {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *Ranking) GetGuild() *Ranking_Guild {
	if x != nil {
		return x.Guild
	}
	return nil
}

func (x *Ranking) GetServer() *Ranking_Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Ranking) GetBracketData() uint32 {
	if x != nil {
		return x.BracketData
	}
	return 0
}

func (x *Ranking) GetFaction() int32 {
	if x != nil {
		return x.Faction
	}
	return 0
}

func (x *Ranking) GetAffixes() []uint32 {
	if x != nil {
		return x.Affixes
	}
	return nil
}

func (x *Ranking) GetMedal() string {
	if x != nil {
		return x.Medal
	}
	return ""
}

func (x *Ranking) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Ranking) GetLeaderboard() uint32 {
	if x != nil {
		return x.Leaderboard
	}
	return 0
}

func (x *Ranking) GetTalents() []*Ranking_Talents {
	if x != nil {
		return x.Talents
	}
	return nil
}

func (x *Ranking) GetGear() []*Ranking_Gear {
	if x != nil {
		return x.Gear
	}
	return nil
}

type Ranking_Report struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code      string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	FightID   uint32 `protobuf:"varint,2,opt,name=fightID,proto3" json:"fightID,omitempty"`
	StartTime uint64 `protobuf:"varint,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
}

func (x *Ranking_Report) Reset() {
	*x = Ranking_Report{}
	if protoimpl.UnsafeEnabled {
		mi := &file_characterRankings_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ranking_Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ranking_Report) ProtoMessage() {}

func (x *Ranking_Report) ProtoReflect() protoreflect.Message {
	mi := &file_characterRankings_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ranking_Report.ProtoReflect.Descriptor instead.
func (*Ranking_Report) Descriptor() ([]byte, []int) {
	return file_characterRankings_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Ranking_Report) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Ranking_Report) GetFightID() uint32 {
	if x != nil {
		return x.FightID
	}
	return 0
}

func (x *Ranking_Report) GetStartTime() uint64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

type Ranking_Guild struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Faction int32  `protobuf:"varint,3,opt,name=faction,proto3" json:"faction,omitempty"`
}

func (x *Ranking_Guild) Reset() {
	*x = Ranking_Guild{}
	if protoimpl.UnsafeEnabled {
		mi := &file_characterRankings_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ranking_Guild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ranking_Guild) ProtoMessage() {}

func (x *Ranking_Guild) ProtoReflect() protoreflect.Message {
	mi := &file_characterRankings_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ranking_Guild.ProtoReflect.Descriptor instead.
func (*Ranking_Guild) Descriptor() ([]byte, []int) {
	return file_characterRankings_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Ranking_Guild) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Ranking_Guild) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ranking_Guild) GetFaction() int32 {
	if x != nil {
		return x.Faction
	}
	return 0
}

type Ranking_Server struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Region string `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
}

func (x *Ranking_Server) Reset() {
	*x = Ranking_Server{}
	if protoimpl.UnsafeEnabled {
		mi := &file_characterRankings_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ranking_Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ranking_Server) ProtoMessage() {}

func (x *Ranking_Server) ProtoReflect() protoreflect.Message {
	mi := &file_characterRankings_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ranking_Server.ProtoReflect.Descriptor instead.
func (*Ranking_Server) Descriptor() ([]byte, []int) {
	return file_characterRankings_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Ranking_Server) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Ranking_Server) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ranking_Server) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type Ranking_Talents struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id       uint32 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	TalentID uint32 `protobuf:"varint,3,opt,name=talentID,proto3" json:"talentID,omitempty"`
	Points   uint32 `protobuf:"varint,4,opt,name=points,proto3" json:"points,omitempty"`
	Icon     string `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
}

func (x *Ranking_Talents) Reset() {
	*x = Ranking_Talents{}
	if protoimpl.UnsafeEnabled {
		mi := &file_characterRankings_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ranking_Talents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ranking_Talents) ProtoMessage() {}

func (x *Ranking_Talents) ProtoReflect() protoreflect.Message {
	mi := &file_characterRankings_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ranking_Talents.ProtoReflect.Descriptor instead.
func (*Ranking_Talents) Descriptor() ([]byte, []int) {
	return file_characterRankings_proto_rawDescGZIP(), []int{1, 3}
}

func (x *Ranking_Talents) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ranking_Talents) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Ranking_Talents) GetTalentID() uint32 {
	if x != nil {
		return x.TalentID
	}
	return 0
}

func (x *Ranking_Talents) GetPoints() uint32 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *Ranking_Talents) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

type Ranking_Gear struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Quality   string   `protobuf:"bytes,2,opt,name=quality,proto3" json:"quality,omitempty"`
	Id        uint32   `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Icon      string   `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	ItemLevel string   `protobuf:"bytes,5,opt,name=itemLevel,proto3" json:"itemLevel,omitempty"`
	BonusIDs  []string `protobuf:"bytes,6,rep,name=bonusIDs,proto3" json:"bonusIDs,omitempty"`
}

func (x *Ranking_Gear) Reset() {
	*x = Ranking_Gear{}
	if protoimpl.UnsafeEnabled {
		mi := &file_characterRankings_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ranking_Gear) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ranking_Gear) ProtoMessage() {}

func (x *Ranking_Gear) ProtoReflect() protoreflect.Message {
	mi := &file_characterRankings_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ranking_Gear.ProtoReflect.Descriptor instead.
func (*Ranking_Gear) Descriptor() ([]byte, []int) {
	return file_characterRankings_proto_rawDescGZIP(), []int{1, 4}
}

func (x *Ranking_Gear) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ranking_Gear) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *Ranking_Gear) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Ranking_Gear) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Ranking_Gear) GetItemLevel() string {
	if x != nil {
		return x.ItemLevel
	}
	return ""
}

func (x *Ranking_Gear) GetBonusIDs() []string {
	if x != nil {
		return x.BonusIDs
	}
	return nil
}

var File_characterRankings_proto protoreflect.FileDescriptor

var file_characterRankings_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x52, 0x61, 0x6e, 0x6b, 0x69,
	0x6e, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8a, 0x01, 0x0a, 0x14, 0x43, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x50, 0x61,
	0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x68, 0x61, 0x73, 0x4d, 0x6f, 0x72,
	0x65, 0x50, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x68, 0x61,
	0x73, 0x4d, 0x6f, 0x72, 0x65, 0x50, 0x61, 0x67, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x24, 0x0a, 0x08, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x72, 0x61,
	0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x99, 0x08, 0x0a, 0x07, 0x52, 0x61, 0x6e, 0x6b, 0x69,
	0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x70, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x68, 0x61, 0x72, 0x64,
	0x4d, 0x6f, 0x64, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0d, 0x68, 0x61, 0x72, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x72, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x69,
	0x6e, 0x67, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x12, 0x24, 0x0a, 0x05, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64,
	0x52, 0x05, 0x67, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x27, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e,
	0x67, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x12, 0x20, 0x0a, 0x0b, 0x62, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x62, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x66, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x66, 0x66, 0x69, 0x78, 0x65, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x07, 0x61,
	0x66, 0x66, 0x69, 0x78, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x18,
	0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62,
	0x6f, 0x61, 0x72, 0x64, 0x12, 0x2a, 0x0a, 0x07, 0x74, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x11, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e,
	0x54, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x07, 0x74, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x73,
	0x12, 0x21, 0x0a, 0x04, 0x67, 0x65, 0x61, 0x72, 0x18, 0x12, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x61, 0x72, 0x52, 0x04, 0x67,
	0x65, 0x61, 0x72, 0x1a, 0x54, 0x0a, 0x06, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x69, 0x67, 0x68, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x66, 0x69, 0x67, 0x68, 0x74, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x1a, 0x45, 0x0a, 0x05, 0x47, 0x75, 0x69,
	0x6c, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x66, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x1a, 0x44, 0x0a, 0x06, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x1a, 0x75, 0x0a, 0x07, 0x54, 0x61, 0x6c, 0x65, 0x6e, 0x74,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x49,
	0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x74, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x49,
	0x44, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x1a, 0x92, 0x01,
	0x0a, 0x04, 0x47, 0x65, 0x61, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x71, 0x75,
	0x61, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x71, 0x75, 0x61,
	0x6c, 0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x74, 0x65, 0x6d,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x74, 0x65,
	0x6d, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x49,
	0x44, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x49,
	0x44, 0x73, 0x42, 0x1a, 0x5a, 0x18, 0x77, 0x6f, 0x77, 0x6c, 0x6f, 0x67, 0x73, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x77, 0x61, 0x72, 0x63, 0x72, 0x61, 0x66, 0x74, 0x6c, 0x6f, 0x67, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_characterRankings_proto_rawDescOnce sync.Once
	file_characterRankings_proto_rawDescData = file_characterRankings_proto_rawDesc
)

func file_characterRankings_proto_rawDescGZIP() []byte {
	file_characterRankings_proto_rawDescOnce.Do(func() {
		file_characterRankings_proto_rawDescData = protoimpl.X.CompressGZIP(file_characterRankings_proto_rawDescData)
	})
	return file_characterRankings_proto_rawDescData
}

var file_characterRankings_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_characterRankings_proto_goTypes = []interface{}{
	(*CharacterRankingPage)(nil), // 0: CharacterRankingPage
	(*Ranking)(nil),              // 1: Ranking
	(*Ranking_Report)(nil),       // 2: Ranking.Report
	(*Ranking_Guild)(nil),        // 3: Ranking.Guild
	(*Ranking_Server)(nil),       // 4: Ranking.Server
	(*Ranking_Talents)(nil),      // 5: Ranking.Talents
	(*Ranking_Gear)(nil),         // 6: Ranking.Gear
}
var file_characterRankings_proto_depIdxs = []int32{
	1, // 0: CharacterRankingPage.rankings:type_name -> Ranking
	2, // 1: Ranking.report:type_name -> Ranking.Report
	3, // 2: Ranking.guild:type_name -> Ranking.Guild
	4, // 3: Ranking.server:type_name -> Ranking.Server
	5, // 4: Ranking.talents:type_name -> Ranking.Talents
	6, // 5: Ranking.gear:type_name -> Ranking.Gear
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_characterRankings_proto_init() }
func file_characterRankings_proto_init() {
	if File_characterRankings_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_characterRankings_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CharacterRankingPage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_characterRankings_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ranking); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_characterRankings_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ranking_Report); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_characterRankings_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ranking_Guild); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_characterRankings_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ranking_Server); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_characterRankings_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ranking_Talents); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_characterRankings_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ranking_Gear); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_characterRankings_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_characterRankings_proto_goTypes,
		DependencyIndexes: file_characterRankings_proto_depIdxs,
		MessageInfos:      file_characterRankings_proto_msgTypes,
	}.Build()
	File_characterRankings_proto = out.File
	file_characterRankings_proto_rawDesc = nil
	file_characterRankings_proto_goTypes = nil
	file_characterRankings_proto_depIdxs = nil
}
